// "AI best match" heuristic scorer (Panel 3.5) — backs GET /api/matches/best-ai.
//
// ─── WHY THIS IS A HEURISTIC, NOT REAL ASTROLOGY ───────────────────────────────
// src/lib/horoscope.ts states the platform's rule plainly: "A language model must
// NEVER produce the planetary positions in a chart... users make marriage decisions
// on this." Real Vedic compatibility (Porutham) needs precise nakshatra pada and
// planetary positions from an ephemeris-backed engine — POST /api/horoscope/compute
// is still a stub (501) here, so that data doesn't exist yet. This scorer does NOT
// pretend otherwise: it's a simple attribute-overlap heuristic (exact nakshatra/rashi
// match plus the same partner-preference signals server/lib/matchSuggestion.js
// already uses), labeled "AI-generated" precisely because it is NOT an astrologer's
// or a real compatibility engine's determination. AI_MATCH_DISCLAIMER below is
// mandatory wherever these results are shown — see Panel 3.5's compliance
// requirement — and the frontend must render it every time, not just once.
import { oppositeGender } from './gender.js'

export const AI_MATCH_DISCLAIMER =
  'This best-match suggestion is generated by an automated compatibility heuristic, not by an astrologer. ' +
  'It is not an astrological determination. Please consult your family astrologer before making any decisions based on horoscope compatibility.'

/** Exported for GET /api/profiles' Elite-only minCompatibility filter, which needs
 * the same scoring rule without pulling in computeBestMatches' own candidate query. */
export function compatibilityScore(user, candidate) {
  let s = 0
  let max = 0

  max += 30
  if (user.nakshatra && candidate.nakshatra && user.nakshatra === candidate.nakshatra) s += 30

  max += 20
  if (user.rashi && candidate.rashi && user.rashi === candidate.rashi) s += 20

  max += 20
  if (user.partnerReligion && candidate.religion && user.partnerReligion.toLowerCase() === candidate.religion.toLowerCase()) s += 20

  max += 15
  if (user.partnerLocation && candidate.city && user.partnerLocation.toLowerCase() === candidate.city.toLowerCase()) s += 15

  max += 10
  if (user.caste && candidate.caste && user.caste === candidate.caste) s += 10

  max += 5
  if (user.motherTongue && candidate.motherTongue && user.motherTongue === candidate.motherTongue) s += 5

  return max ? Math.round((s / max) * 100) : 0
}

/** Returns up to `limit` best-scoring opposite-gender candidates, best first, each with a 0-100 `compatibilityScore`. */
export async function computeBestMatches(prisma, user, limit = 5) {
  const targetGender = oppositeGender(user.gender)
  if (!targetGender) return []

  const candidates = await prisma.user.findMany({
    where: { gender: targetGender, status: 'active', approved: true, id: { not: user.id } },
    select: {
      id: true, name: true, city: true, religion: true, caste: true, motherTongue: true,
      nakshatra: true, rashi: true, dob: true, avatar: true, idVerified: true, photoVerified: true,
    },
    take: 300,
  })

  return candidates
    .map((c) => ({ ...c, compatibilityScore: compatibilityScore(user, c) }))
    .sort((a, b) => b.compatibilityScore - a.compatibilityScore)
    .slice(0, limit)
}
